### ISSUE TITLE
Autocomplete mixin absolute uri

### ISSUE THREAD

**Issue by mblasi** [got5/tapestry5-jquery#263]
Hi all, I'm using the awsome got5-jquery' autocomplete mixin, and it is woking perfectly on localhost.
Since I deployed the application on a erver, I get this error on the client:

"XMLHttpRequest cannot load http://localhost:9090/office/list.cuit:autocomplete. Origin http://bvdev54.myhost.local is not allowed by Access-Control-Allow-Origin"

I think that it is because of the use of link.toAbsoluteURI() instead of link.toURI() as tapestry' core autocomplete mixin does.

What do you think?
Could any of you make it run on another environment than localhost?

Regards,
Matías.

**Comment by rouazana** [comment]
Hi,

Could this fix be backported in the 3.3 branch please?

Regards,
Raphaël Ouazana.

**Comment by ffacon** [comment]
Hi Raphaël,

The fix is now available in 3.3.11.
Thank's for the feedback.

Regards,
François Facon
