### ISSUE TITLE
What to do with all these out-dated components?

### ISSUE THREAD

**Issue by criedel** [got5/tapestry5-jquery#346]
I just stumbled upon the reveal component, which I tried to use for a simple website project. It’s kind of broken since its calculation for the modal panel location is limited seems is wrong even in my simple setup.
Then I looked up the code in jquery.reveal.js – it’s dated 2010. The current version is now part of the “Foundation Framework”.

I don’t know how valuable it is to maintain an outdated component. In the past I just coded this myself and it’s not a hard thing to do if your use-case is clear.

Same out-dated-ness applies to a few other components as well:
jeditable: dated 2009, update available from 2013,
jquery scrollExtend: 2009, update available from 2014,
fileupload: became fineuploader, 
...to name a few.

How about a little cleaning up?

**Comment by ffacon** [comment]
Hello Christian, 

I know that some of our users that some of our users are attached to components that we may seem basic. Internal asked me to provide backward compatibility for our components. So I would prefer to avoid the removal of existing components.

I agree that we need to update outdated components.

**Comment by Gillespie59** [comment]
+1 for updating existing jQuery widget

**Comment by criedel** [comment]
And what do we do with components that rely on outdated third-party libs?
If no one here cares to roll a custom version of those components and support them, I think we should deprecate them.
AjaxUpload, which relies on file-uploader, which became fine-uploader also changed its license. I think we cannot bundle the current version witht this lib, because of license issues, right?

Maybe we do it the jQuery-way and move outdated features into a legacy-project. That way we could get rid of those old components while still supporting an easy to use path for users who rely on removed features. New users will be happy to bundle less outdated stuff into their apps.

**Comment by ffacon** [comment]
I created a spin off for ajax Upload. see Tapestry5-jquery-upload. This way, it will be possible to continue to use this component without polluting Tapestry5-jquery with outdated version file-uploader.

**Comment by criedel** [comment]
Awesome! So what’s the plan then? 
1) Keeping it compatible with tapestry5-jquery, while still using the outdated file-uploader, i.e. a legacy support module
2) Actually upgrading the entire component to the latest fine-uploader, i.e. not being backwards-compatible
3) Doing both 1) in a legacy branch releasing ´´´tapestry5-jquery-upload-legacy´´´ packages and 2) in the master branch

I'd go with option 3) for at least one legacy release once T5.4 is final.

**Comment by Gillespie59** [comment]
I am not agree with your last commits @ffacon. We should deprecate first this component, and remove it in the next release.

**Comment by criedel** [comment]
There’s no problem with adding the upload-library in the next release as a dependency. Users wouldn’t notice I guess.

**Comment by Gillespie59** [comment]
You are right. We use the same namespace. Only if we still the saem version of the jQuery widget. 
If we update to the newest version, as your proposed, 
We should do a first release with the legacy version ! Add javadoc directly in this release with the possible modications we can have with the newest version. 
And after that, update the widget with the version of fine-uploader.

**Comment by criedel** [comment]
I'm currently working on a proper fine-uploader integration with T5.4 – you guys don’t have an unreleased  almost ready code base that I could continue working on?

**Comment by Gillespie59** [comment]
for which projects ? TjQ or new Upload component library ?

**Comment by criedel** [comment]
The new one. I found a few hints here[0] about a possible setup but there’re still some things to turn this into a component.

[0] http://stackoverflow.com/questions/27760867/tapestry-fine-uploader-implementation

**Comment by ffacon** [comment]
@criedel Option 3) sound well for me too.

So the lastest  "free" version of fileUpload seems to be https://github.com/FineUploader/fine-uploader/tree/5.0.9 
Does anyone know if  this version is compatible with current java side?

**Comment by criedel** [comment]
No, the AjaxUploadDecoder/AjaxUploadServletRequestFilter cannot handle the upload requests that are sent by the 5.x branch. There are now more ways how to upload a file and I think some of the request parameters changed so that might be the cause why the old server side mechanism doesn’t get to extract an UploadedFile.

**Comment by rnicholus** [comment]
Feel free to let me know if you run into any issues integrating Fine Uploader :wink:

**Comment by criedel** [comment]
Thanks :) 
I’m tried to integrate it with the usual mix of tapestry-upload’s MultipartDecoder and the custom AjaxUploadDecoder that we previously had been using (just to make the whole thing compatible with Tapestry’s ```org.apache.tapestry5.upload.services.UploadedFile```). Unfortunately there’s something not working out with the two decoders and now I just started to translate your examples into Tapestry Filters and Services / Decoders. That’s kinda tedious.

Well... the chunked upload feature gives me a headache. If I implement this one in the library, it might be hard(er) to integrate it in a clustered environment where each chunk might end up on a different server.

Then there’s this license issue: 5.0.9 was still released under GPL3, but it clearly stated to be only used for non-commercial products, just like the current version’s license. I’m no lawyer, but aren’t they kind of similar? Then again, we do not want to be stuck with an unsupported branch, do we?
Also, is it okay to bundle the whole library or would you all think it’s better to let the library’s user integrate the actual fine-uploader version? And what should be the version of the TjQ-Upload anyway?

**Comment by rnicholus** [comment]
There are a **lot** of advantages to the file chunking feature.  This allows for more efficient retries (if the upload fails midway through) resuming an upload from a previous session, pause/continue uploads, etc.  But, you can disable chunking if you really want via the JS config.  

Regarding the license, the intent of our previous model was for commercial users to purchase a license, but this was not enforceable via GPLv3.  Our new license codifies our intent.  Non-commercial users can use Fine Uploader for free.  We never backport bug fixes or features, so all new work will be under the new license model.

You can certainly include the library in your project, as long as you make the licensing for Fine Uploader clear to your users.  Otherwise, you can link to our download page.  You can instruct users to pull Fine Uploader via npm as well.

**Comment by ffacon** [comment]
Hello Ray,

Will it be ok for you if for version upper than 5.0.9, we add the following comments in the readme file related to https://github.com/got5/tapestry5-jquery-upload. 

" If you are developing an open-source or free product and will not derive any money from the product using Fine Uploader, you may use Fine Uploader free of charge under the Widen Commercial License (http://fineuploader.com/licensing.html ). 

 if you are going to use Fine Uploader for a commercial product or in a commercial setting or if you want to have support, you must purchase a license at http://fineuploader.com/purchase_form.html "

**Comment by rnicholus** [comment]
Yes, that should be fine as long as the header of the JavaScript file remains in-tact as well.  You can change that last link to http://fineuploader.com/purchase, as it will re-direct to the proper page (and looks a bit nicer).  

I would say the same is true for 5.0.9 and earlier as that was our intent of the licensing model.

**Comment by rnicholus** [comment]
Note that there will be some substantial UI and accessibility enhancements coming in 5.2.0.  New features are bug fixes are the primary reason why you may want to stay current/  We've doing our best to ensure none of these changes in the next version are breaking though.  

For future user, we follow semantic versioning very strictly.  This should make it clear what a release contains (bugfixes, features, or breaking changes).

**Comment by rnicholus** [comment]
Note that as of Fine Uploader 5.9.0, the project is once again MIT licensed.
