### ISSUE TITLE
Datatable cause an issue on Websphere Application Server

### ISSUE THREAD

**Issue by Tokinoki** [got5/tapestry5-jquery#347]
Environnement :
	Tapestry 5.3.7
	Tapestry5-jQuery 3.3.7
	Websphere Application Server 8.5
	IBM J9 VM (build 2.6, JRE 1.7.0 AIX ppc64-64 Compressed References 20141013_217026)

When we try to access a page containing a datatable with with mode=true (ajax mode) we get this error : "DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error." 

When we inspect the ajax response we can see that there is an empty JSON object {} at the end of the response which is an invalid JSON object.

https://issues.apache.org/jira/browse/TAP5-1854
https://issues.apache.org/jira/browse/TAPESTRY-2619

Everything work fine on tomcat 7.

**Comment by Tokinoki** [comment]
I think the problem is in DefaultDataTableModel.java in the getResponse method

/**
 * Even if it will be done once again in AjaxComponentEventRequestHandler , we must call partialRenderer.renderPartialPageMarkup() here to
 * "flush" the PartialMarkupRendererFilters that we've added into the JSONArray ! It would be great if we could tell the partialRenderer that
* the job have already been done ...
*/
partialRenderer.renderPartialPageMarkup();

**Comment by adaptivui** [comment]
Hi,

I was not able to reproduce this issue.

Environnement :
Tapestry 5.3.7
Tapestry5-jQuery 3.3.7
 WebSphere Application Server 8.5.5.2
Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_67-b01

Could you share an example in order to reproduce your issue?
