### ISSUE TITLE
3.4.2 and earlier don't validate negative numbers

### ISSUE THREAD

**Issue by rfrovarp** [got5/tapestry5-jquery#350]
Versions 3.4.2 and earlier don't validate negative numbers. As Tapestry 5.4 hasn't been released, I haven't checked out 4.x. The issue is in tapestry-jquery.js. In the process of trying to convert a string to a number, it ends up being --1 for an input of -1. Looks like the call to Number() is returning NaN from there. It might also have the problem of double appending the decimal separator as well.

**Comment by got5** [comment]
Hello rfrovarp,
Could you give us more details about your issue?

**Comment by rfrovarp** [comment]
Sorry about the late reply. There's the chunk of if if/else statements to check the various parts of the number one character at a time. At the end of the if/else statements it always adds on the character. So something like a minus symbol is added to the string by the if statement and the always statement. The always statement needs to be made an else. Here's the patch:

--- a/src/main/resources/org/got5/tapestry5/jquery/tapestry-jquery.js
+++ b/src/main/resources/org/got5/tapestry5/jquery/tapestry-jquery.js
@@ -938,10 +938,11 @@
                                                        throw Tapestry.Messages.notAnInteger;
 
                                                ch = ".";
-                                       } else if (ch < "0" || ch > "9")
+                                       } else if (ch < "0" || ch > "9") {
                                                throw Tapestry.Messages.invalidCharacter;
-
-                                       canonical += ch;
+                                       } else {
+                                               canonical += ch;
+                                       }
                                }
                                ;

**Comment by ffacon** [comment]
Hello rfrovarp,

Thank you for the patch.
Best Regards
François
