### ISSUE TITLE
Update out-dated reveal components

### ISSUE THREAD

**Issue by ffacon** [got5/tapestry5-jquery#351]
thisis issue is link to https://github.com/got5/tapestry5-jquery/issues/346

the plugin  jquery.reveal.js – it’s dated 2010. The current version is now part of the “Foundation Framework”.

**Comment by ffacon** [comment]
I created a spin off for reveal. see https://github.com/got5/tapestry5-foundation. This way, it will be possible to continue to use this component with the latest version provided by ZURB.

**Comment by Gillespie59** [comment]
why do you create an external librairy ? for the licence ? foundation use the MIT licence, used by other Tapestry jQuery : jcrop, jeditable, ...

**Comment by ffacon** [comment]
it's about modularity. Reveal is part of foundation and come now with css and foundation.js and lot's of js components. so it deserve now a module. see http://foundation.zurb.com/docs/components/kitchen_sink.html
