### ISSUE TITLE
3.4.2 - Confirm Mixin - allow non-int values for height (and width, if implemented) when useDefaultConfirm=false

### ISSUE THREAD

**Issue by danowar2k** [got5/tapestry5-jquery#353]
When using the jquery dialog, you can set the height of the dialog box, but only using int values.

The jquery dialog allows height="auto". It would be nice if the confirm mixin would allow that, too.

Or better yet, if the Confirm Mixin uses the Jquery dialog, just allow a parameter "params" like the jquery dialog and let the user configure some dialog values that way.

**Comment by got5** [comment]
Hello again.

Could you propose a sample based on https://github.com/got5/tapestry5-jquery/blob/maint-3.4.x/src/test/java/org/got5/tapestry5/jquery/pages/JQueryConfirm.java that reproduce you problem?

**Comment by Gillespie59** [comment]
Just a quick look to the code 

```
@Parameter(value = "180", defaultPrefix = BindingConstants.LITERAL)
private int height;
```

**Comment by danowar2k** [comment]
Hi, is the first comment autogenerated?
I'm trying to discern what I should do. Should I paste the example setting "height" to "auto" so that the component breaks? Or does pasting part of the Confirm Mixin code suffice?

@Gillespie59 Is your comment a hint for the comment above or a hint for me?

**Comment by Gillespie59** [comment]
a hint for the comment ;) 
We should update the type of the height pararmeter.

**Comment by ffacon** [comment]
For compatiblity reason, I would keep the type to Int. 
I would propose to add a JSONObject  as new Parameter called params.
By this way after a merge for object with the default configuration we will let people select the right type height and width and for any parameters.

**Comment by Gillespie59** [comment]
OK for me.
