### ISSUE TITLE
GMap component throws a javascript error with tapestry 5.4-beta-30

### ISSUE THREAD

**Issue by balapal** [got5/tapestry5-jquery#362]
Hi,

I am trying to use GMap component and get *"RequireJS error: require: isEmpty is not defined"* error message in javascript console.

It looks like it is missing the isEmpty function in GMap.js:
```javascript
requirejs.config({
    "shim" : {
        "tjq/vendor/components/gmap/gmap3" : [ "async!http://maps.google.com/maps/api/js?sensor=false", "jquery" ]
    }
});

define([ "tjq/vendor/components/gmap/gmap3" ], function() {
    return function(spec) {

        if (isEmpty(specs.params)) {

            jQuery('#' + specs.id).gmap3();

        } else {

            jQuery('#' + specs.id).gmap3(specs.params);
        }
    };
});
```

**Am I missing some javascript dependencies here? Or is GMap is not yet compatible with tapestry 5.4-beta-30?**

** Further details: **
TML:
`<div t:type="jquery/gmap" t:id="map" ></div>`

Java
```java
public JSONObject getOptions()
    {
        final JSONObject json = new JSONObject();
        return json;
    }
```

**Libaries:**
* tapestry 5.4-beta-30
* tapestry5-jquery 4.0.1-beta-26

**Browser:** Chrome

**Comment by balapal** [comment]
tapestry 5.3 compatible https://github.com/got5/tapestry5-jquery/blob/6c09d7f10ff2f66cf6fc814134e7dfa84e319d29/src/main/resources/org/got5/tapestry5/jquery/assets/components/gmap/GMap.js seems to define the isEmpty method whereas the tapestry 5.4 version does not, but still uses it: https://github.com/got5/tapestry5-jquery/blob/6c09d7f10ff2f66cf6fc814134e7dfa84e319d29/src/main/resources/META-INF/modules/tjq/GMap.js

**Comment by ffacon** [comment]
Thanks you for the feedback and your investigation.
This issue should fix now.

**Comment by balapal** [comment]
Thanks for the fix.
Is it possible to publish a new beta release with this fix included?
Cheers

**Comment by ffacon** [comment]
Next release for Tapestry5-jquery will be available on maven-central.
Could you try this version http://search.maven.org/#artifactdetails%7Corg.got5%7Ctapestry5-jquery%7C4.0-beta-29%7Cjar

**Comment by balapal** [comment]
Looks good. Thanks a lot @ffacon. ;)
