### ISSUE TITLE
Tapestry5: jQuery.dialog not work with DataTables

### ISSUE THREAD

**Issue by mmtuong** [got5/tapestry5-jquery#365]
Now we are using DataTable for showing the finder result. In one cell there is a Actionlink delete-button. But if we click on the delete button, no jQuery.dialog is displayed. The code for that I have posted at below.
Thanks for analyzing...
Template:

<t:jquery.datatable t:id="finderResultGrid" t:source="finderCallback.finderGridDataSource"
t:rowsPerPage="prop:rowsPerPageInitial" t:include="prop:colsToInclude" t:exclude="prop:colsToExclude"
t:model="finderResultGridModel" t:options="finderResultGridOptions"
t:mode="false" t:row="finderResultRow" t:tableInformation="finderResultGridInformation" t:add="action">
....

<p:actionCell><t:modcommon.actionLinkBuilder....

-------------------------------------------------------------------------------------------------------------------------------
Code behind the delete button:

jQuery(document).ready(function($) { $('#delete_mtmmtm').click(function (e)
{ e.preventDefault();$('#form_delete_popup').dialog('open');$( '#delete_pkTargetField' ).val('bXRtbXRt');$( '#delete_pkTargetField_hash' ).val('974AF96FBBCCD2FF103DABF6EB5CF3D5F66EB8179CFF73A2AA629633F5B2B425');}

);});

-------------------------------------------------------------------------------------------------------------------------------
Calling function:

<script type="text/javascript">
// due to use of jQuery data table we have to add the class "k-actions"
// to each last td of each tr in table with id "finderResultGrid"

jQuery(document).ready(function() {

jQuery( "#finderResultGrid tr td:last-of-type" ).addClass( "k-actions" );

$(function() {
var dialog1 = $("#form_delete_popup").dialog(
{ autoOpen: false, height: 150, width: 350, modal: true, title: 'Delete user', }

);
});
});
</script>

**Comment by ffacon** [comment]
it is impossible to answer with partial code. 
could you provide a real test case? 
I need working page that reproduce the problem. I suggest you to get some inspirations form   
https://github.com/got5/tapestry5-jquery/blob/master/src/test/java/org/got5/tapestry5/jquery/pages/DataTables.java
and  https://github.com/got5/tapestry5-jquery/blob/master/src/test/resources/org/got5/tapestry5/jquery/pages/DataTables.tml

**Comment by mmtuong** [comment]
hi,
sorry, it's to difficult to create a real test case...causing on the tml and ref. class file. But if you have the DataTable you can put a actionlink with calling the scriptfuncton for opening a modal dialog of jQuery i.e. confirmation dialog. Hope that you can reproduce this problem.

**Comment by mmtuong** [comment]
Handled by SUPPORT-8289.
