### ISSUE TITLE
No more reposotory available...

### ISSUE THREAD

**Issue by BHMath** [got5/tapestry5-jquery#369]
http://nexus.devlab722.net/nexus/content/repositories/releases/org/got5/tapestry5-jquery/3.3.7/ is unreachable

devlab nexus are down. Please provide a new repository...

**Comment by ffacon** [comment]
as mention in ReadMe http://nexus.devlab722.net/nexus/content/repositories/releases will stop at the end November 2015, 

The latest releases for 5.4 and 5.3 are now available at Maven Central. https://repo1.maven.org/maven2/org/got5/tapestry5-jquery/
