### ISSUE TITLE
4.0.0 is missing in central maven repository

### ISSUE THREAD

**Issue by thackel** [got5/tapestry5-jquery#370]
Only the RC-1 is available in the main repository even when the 4.0.0 is available here in the master.
https://repo1.maven.org/maven2/org/got5/tapestry5-jquery/

Merry Christmas and a happy new Year!

**Comment by got5** [comment]
Hello Thomas,

The jar is also available here  
http://central.maven.org/maven2/org/got5/tapestry5-jquery/4.0.0/tapestry5-jquery-4.0.0.jar

is it ok for you now?

Happy new Year to you and your family!

**Comment by thackel** [comment]
Well done, 4.0.0 is now available in the central repository.
