### ISSUE TITLE
Pagescroll restriction fetching data

### ISSUE THREAD

**Issue by Pr0b** [got5/tapestry5-jquery#371]
Is there a way how to pass restrictions to the [Pagescroll template]( tapestry5-jquery/src/test/java/org/got5/tapestry5/jquery/pages/PageScroll.java )? For example to fetch data only at the bottom of the page and only for scrolling down.

**Comment by got5** [comment]
I don't know well the jQuery scrollExtend Plugin but you can have a look at the source code of this plugin at 

https://github.com/got5/tapestry5-jquery/blob/v3.4.2/src/main/resources/org/got5/tapestry5/jquery/assets/components/pagescroll/jquery.scrollExtend.min.js


PageScroll component has the following parameter

@Parameter 
private JSONObject params;

that can be use to pass a JSONObject to the scrollExtend plugin.

For more detail, see the script make the link between the PageScroll component  and the jQuery plugin available at https://github.com/got5/tapestry5-jquery/blob/v3.4.2/src/main/resources/org/got5/tapestry5/jquery/assets/components/pagescroll/PageScroll.js.


I not sure that this jQuery Plugin has the restrictions you are looking for.
