### ISSUE TITLE
CustomDatepicker mixin not working

### ISSUE THREAD

**Issue by nquirynen** [got5/tapestry5-jquery#373]
Hi,

I'm upgrading to tapestry:5.4.0 and tapestry-jquery:4.0.0.

I have the following .tml:

```
    <t:form>
        <t:datefield t:id="someDateField"
                t:value="someDate"
                t:mixins="jquery/CustomDatepicker"
                t:customdatepicker.params="params" />
    </t:form>
```

and in my java code:
```
    @Property
    private LocalDate someDate;

    public JSONObject getParams() {
        JSONObject params = new JSONObject();
        params.put("dateFormat", "dd-mm-yy");
        params.put("changeMonth", true);
        params.put("changeYear", true);
        return params;
    }
```

In the browsers console I do see the following:

> Invoking tjq/customdatepicker({"selector":"#someDateField","params":{"dateFormat":"dd-mm-yy","changeMonth":true,"changeYear":true,"selector":"#someDateField"}})

But for some reason the parameters are not being applied to the component...

I have noticed that it does work when it is inside a Zone and when the Zone is rerendered, but cannot find out why...

Example code you can test yourself:

**CustomDatePickerTest.tml**

```
<!DOCTYPE html>
<html xmlns:t="http://tapestry.apache.org/schema/tapestry_5_4.xsd"
	xmlns:p="tapestry:parameter">

<t:zone t:id="zone" id="zone">
    <t:form>
        <t:datefield t:id="someDateField" t:value="someDate"
            t:mixins="jquery/CustomDatepicker" t:customdatepicker.params="params" />
    </t:form>
</t:zone>

<t:eventlink t:async="true" t:event="rerender">Rerender</t:eventlink>

</html>
```

**CustomDatePicker.java**

```
public class CustomDatePickerTest {

    @Property
    private LocalDate someDate;
    @Inject
    private AjaxResponseRenderer ajax;
    @InjectComponent
    private Zone zone;

    public JSONObject getParams() {
        JSONObject params = new JSONObject();
        params.put("dateFormat", "dd-mm-yy");
        params.put("changeMonth", true);
        params.put("changeYear", true);
        return params;
    }

    void onRerender() {
        ajax.addRender(zone);
    }
} 
```

When debugging at the line below I found that the element does not have the "hasDatepicker" css class on the initial page render, but does have it when triggering the rerender event (zone update).

https://github.com/got5/tapestry5-jquery/blob/master/src/main/resources/META-INF/modules/tjq/customdatepicker.js#L20

Maybe it has something to do with the order of loading the modules?

This is the output I get in the browsers console which might help:

On regular page render:

> Loading 0 libraries
> Executing 4 inits
> Invoking t5/core/pageinit:focus("someDateField")
> Loaded module t5/core/zone
> Invoking tjq/customdatepicker({"selector":"#someDateField","params":{"dateFormat":"dd-mm-yy","changeMonth":true,"changeYear":true,"yearRange":"c-100:c+100","selector":"#someDateField"}})
> Loaded module t5/core/datefield
> All inits executed

after rerender event:

> Updating content for zone zone
> Executing 3 inits
> Invoking tjq/customdatepicker({"selector":"#someDateField_144ff98629f60f10","params":{"dateFormat":"dd-mm-yy","changeMonth":true,"changeYear":true,"yearRange":"c-100:c+100","selector":"#someDateField_144ff98629f60f10"}})
> Loaded module t5/core/datefield
> Invoking t5/core/pageinit:focus("someDateField_144ff98629f60f10")
> All inits executed

**Comment by ffacon** [comment]
Hello Nathan, 

This should be fix with latest 4.1.1-SNAPSHOT.

François

**Comment by jaferreirog** [comment]
Hello
I have the same problem, but ffacon you talk about tapestry-jquery:4.1.1-SNAPSHOT but in maven repository the last version is tapestry-jquery:4.0.0. Where I can got it???
thanks

**Comment by ffacon** [comment]
Hello 

The snapshot version is available at  
https://oss.sonatype.org/content/repositories/snapshots/org/got5/tapestry5-jquery/4.1.1-SNAPSHOT/
see readme file for maven repository configuration.

Regards
François

**Comment by jaferreirog** [comment]
Thanks ffacon 
but where are readme file ??

**Comment by jaferreirog** [comment]
sorry ffacon I was asleep when I readed your mail.
It´s work all fine.
Thanks. Thanks. Thanks.¡¡¡¡

**Comment by got5** [comment]
Good news! Thanks for the feedback.
