### ISSUE TITLE
CustomDAtepicker

### ISSUE THREAD

**Issue by jaferreirog** [got5/tapestry5-jquery#376]
Hi
I use tapestry 5.4.1 and tapestry5-jquery version 4.1.0 de org.got5.
I configured customdatepicker to show month january day 1 year 2012, but not work correct,
but if I recharge page with Ctrl+F5 Its work fine (but not always)
Somebody can help me please.

**Comment by got5** [comment]
see CustomDatepicker mixin not working #373
