### ISSUE TITLE
Reverse jQuery version to 1.12.2 to avoid jQuery known weaknesses 2432 

### ISSUE THREAD

**Issue by ffacon** [got5/tapestry5-jquery#383]
According to  http://research.insecurelabs.org/jquery/test/ jQuery 1.12.2 is the latest stable version based on 1.x branch with no known weaknesses. Tapestry5-jquery 3.5.1 should use this version.

**Comment by got5** [comment]
Tapestry5-jquery 3.5.1 is available at Maven Central.
This version embed a the latest version of jQuery 1.12.2 & jQuery 2.0.2
https://repo1.maven.org/maven2/org/got5/tapestry5-jquery/3.5.1/
